##Server Information
spring.application.name=TODO-LIST
server.port = 8081
##Databasr configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/todolistdb
spring.datasource.username=postgres
spring.datasource.password=bamenda05
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.datasource.initialization-mode=always
spring.datasource.initialize=true
##spring.datasource.schema=classpath:/schema.sql
spring.datasource.continue-on-error=true

# Swagger config
#springdoc.swagger-ui.path=/swagger-ui/index.html
#springdoc.api-docs.path=/v3/api-docs
#spring.resources.static-locations=classpath:/static/
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
# application.properties
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html


